### PR TITLE
User index view

### PR DESCRIPTION
**Pull request by theofidry**
Related to #50.

**Objective**: provide the basic structure of the users management with all the view. Work on easing the process for CRUD handling by providing a good example of the API calls, instantiation of forms, creation of forms and such.

### Features

* [x] Index view for users
* [x] New form for users
* [x] Edit form for users
* [x] Delete form for users

### Changes

* Changed the behaviour of the role filter for the twig extension FrontExtension:
  * The function of the service used is now a static function
  * The filter now takes the roles array as an input, which avoid to call the service in the controller to add to each user its topRole
* The `FrontBundle\Client\ApiClientInterface` has now a `send()` method and `FrontBundle\Client\ApiClient` implements it
* Added the `FrontBundle\Controller\BaseControllerInterface` to specify some helpers useful for all controllers of the `FrontBundle`; `FrontBundle\Controller\BaseController` now implements it
* Greatly improved test code coverage
* Refactor of the `BaseController` to ease the calls of the client and the decoding of responses
* Good example of form usage
* Upgraded [DunglasApiBundle](https://github.com/dunglas/DunglasApiBundle) version
  * [ ] Requires dunglas/DunglasApiBundle#211
  * NelmioApiDocBundle temporary disabled as causes errors
* Introduced two custom filters for `User`

#### Tests

* Travis now run two Behat processes, one for the API and another for the Front
* Behat contexts can now be tested
* Code coverage now includes Behat contexts

### Bugfix

* Some user fixtures had wrong values for `types`
* User fixtures did not have the proper unique constraint
* ApiClient now throw properly Guzzle exceptions
* BaseController now handles ApiClient exceptions

### CODE REVIEW

**Comment by theofidry** [comment]
@xNok could you take a little look at the added tests and changes in the `BaseController` and `ApiClient` to tell me if it's clear enough?

**Comment by xNok** [comment]
You have refactor for request in BaseContoller - OK

I have take a look at your added tests. I have also start writing basic test and I should write behat step definition to run it.

**Comment by theofidry** [comment]
@xNok almost everything should be good for the first version. I'm still finishing the forms (just the link lacking I think) and it should be good.

What's left after that:
* Add tests
* Add some functionalities
* Clean the code (the code is really clean but I believe it won't hurt a bit to stop and refactor a few things, checking the scrutinizer and such before continuing)

**Comment by theofidry** [comment]
@xNok I still have to merge the PR on DunglasApiBundle and should work like a charm.

**Pull request merged**
